"""HTML reporter — generates a self-contained report with Chart.js."""

from pathlib import Path
from jinja2 import Template

from ..analyzers.core import AnalysisResult

TEMPLATE = Template(
    """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Git Insights — {{ result.repo_name }}</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<style>
  :root { --bg: #0f172a; --surface: #1e293b; --text: #e2e8f0; --accent: #38bdf8; --green: #4ade80; --red: #f87171; --yellow: #facc15; --border: #334155; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }
  h1 { color: var(--accent); margin-bottom: 0.5rem; font-size: 1.8rem; }
  h2 { color: var(--accent); margin: 2rem 0 1rem; font-size: 1.3rem; }
  .subtitle { color: #94a3b8; margin-bottom: 2rem; }
  .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
  .card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 1.2rem; }
  .card .label { font-size: 0.85rem; color: #94a3b8; }
  .card .value { font-size: 1.6rem; font-weight: 700; color: var(--text); margin-top: 0.3rem; }
  table { width: 100%; border-collapse: collapse; background: var(--surface); border-radius: 12px; overflow: hidden; }
  th { background: #334155; text-align: left; padding: 0.8rem 1rem; font-size: 0.85rem; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }
  td { padding: 0.7rem 1rem; border-top: 1px solid var(--border); }
  tr:hover td { background: rgba(56, 189, 248, 0.05); }
  .add { color: var(--green); }
  .del { color: var(--red); }
  .chart-container { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 1.5rem; margin-bottom: 2rem; }
  canvas { max-height: 350px; }
  footer { margin-top: 3rem; text-align: center; color: #64748b; font-size: 0.8rem; }
</style>
</head>
<body>

<h1>📊 {{ result.repo_name }}</h1>
<p class="subtitle">Git Insights Report</p>

<div class="grid">
  <div class="card"><div class="label">Commits</div><div class="value">{{ result.total_commits }}</div></div>
  <div class="card"><div class="label">Authors</div><div class="value">{{ result.total_authors }}</div></div>
  <div class="card"><div class="label">First Commit</div><div class="value" style="font-size:1.1rem">{{ result.first_commit_date }}</div></div>
  <div class="card"><div class="label">Last Commit</div><div class="value" style="font-size:1.1rem">{{ result.last_commit_date }}</div></div>
</div>

{% if contributions %}
<h2>👥 Contributions</h2>
<table>
  <thead><tr><th>Author</th><th>Commits</th><th>Additions</th><th>Deletions</th><th>Files</th></tr></thead>
  <tbody>
  {% for row in contributions %}
    <tr>
      <td>{{ row.author }}</td>
      <td>{{ row.commits }}</td>
      <td class="add">+{{ row.additions }}</td>
      <td class="del">-{{ row.deletions }}</td>
      <td>{{ row.files_touched }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}

{% if hotspots %}
<h2>🔥 File Hotspots</h2>
<table>
  <thead><tr><th>File</th><th>Changes</th><th>Authors</th></tr></thead>
  <tbody>
  {% for row in hotspots %}
    <tr><td>{{ row.file }}</td><td>{{ row.changes }}</td><td>{{ row.authors }}</td></tr>
  {% endfor %}
  </tbody>
</table>
{% endif %}

{% if heatmap_data %}
<h2>⏰ Commit Activity Heatmap</h2>
<div class="chart-container">
  <canvas id="heatmapChart"></canvas>
</div>
{% endif %}

{% if timeline_data %}
<h2>📈 Codebase Size Over Time</h2>
<div class="chart-container">
  <canvas id="timelineChart"></canvas>
</div>
{% endif %}

<footer>Generated by git-insights</footer>

<script>
{% if heatmap_data %}
(() => {
  const data = {{ heatmap_data | safe }};
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  const datasets = days.map((day, i) => ({
    label: day,
    data: data.filter(d => d.day_index === i).map(d => ({ x: d.hour, y: d.commits })),
    backgroundColor: `hsla(${i * 50}, 70%, 60%, 0.8)`,
  }));
  new Chart(document.getElementById('heatmapChart'), {
    type: 'bar',
    data: { labels: Array.from({length: 24}, (_, i) => `${i}:00`), datasets },
    options: {
      responsive: true,
      plugins: { legend: { labels: { color: '#e2e8f0' } } },
      scales: {
        x: { stacked: true, ticks: { color: '#94a3b8' }, grid: { color: '#1e293b' } },
        y: { stacked: true, ticks: { color: '#94a3b8' }, grid: { color: '#1e293b' } },
      },
    },
  });
})();
{% endif %}

{% if timeline_data %}
(() => {
  const data = {{ timeline_data | safe }};
  new Chart(document.getElementById('timelineChart'), {
    type: 'line',
    data: {
      labels: data.map(d => d.date),
      datasets: [{
        label: 'Cumulative Lines',
        data: data.map(d => d.cumulative_size),
        borderColor: '#38bdf8',
        backgroundColor: 'rgba(56, 189, 248, 0.1)',
        fill: true,
        tension: 0.3,
        pointRadius: 2,
      }],
    },
    options: {
      responsive: true,
      plugins: { legend: { labels: { color: '#e2e8f0' } } },
      scales: {
        x: { ticks: { color: '#94a3b8', maxTicksLimit: 12 }, grid: { color: '#1e293b' } },
        y: { ticks: { color: '#94a3b8' }, grid: { color: '#1e293b' } },
      },
    },
  });
})();
{% endif %}
</script>
</body>
</html>
"""
)


def generate_html(result: AnalysisResult, output_path: str) -> None:
    """Generate a self-contained HTML report."""
    import json

    contributions = result.contributions.to_dict("records") if not result.contributions.empty else []
    hotspots = result.hotspots.to_dict("records") if not result.hotspots.empty else []

    heatmap_data = ""
    if not result.activity.empty:
        heatmap_data = json.dumps(result.activity.to_dict("records"))

    timeline_data = ""
    if not result.timeline.empty:
        timeline_data = json.dumps(
            result.timeline[["date", "cumulative_size"]].to_dict("records")
        )

    html = TEMPLATE.render(
        result=result,
        contributions=contributions,
        hotspots=hotspots,
        heatmap_data=heatmap_data,
        timeline_data=timeline_data,
    )

    Path(output_path).write_text(html, encoding="utf-8")
